---
- name: Install oracledb_exporter on UBI9
  hosts: all
  become: yes
  roles:
    - role: oracledb_exporter
      vars:
        oracle_db_host: oracle-xe
        oracle_db_port: 1521
        oracle_db_service: XEPDB1
        oracle_db_user: oracledb_exporter
        oracle_db_password: exporter_pass
        oracle_admin_password: SysPassword1
